### ISSUE TITLE
Encountering "attempt to shift left with overflow" with 64-bit slice

### ISSUE THREAD

**Issue by kulp** [myrrlyn/bitvec#58]
I am newly trying to use the `BitField` API (`.load()` in particular), and I might be doing something wrong, but I found that the following code panics :
```
#[test]
fn fails_with_u64() {
    use bitvec::prelude::*;

    // The numeric value in `val` makes no difference
    let val = 0_u64; // u32, u16, u8 pass; u64 fails
    // Lsb0 vs. Msb0 makes no difference
    let boxed = BitBox::new(val.bits::<Msb0>());
    let _: u64 = boxed[0..64].load(); // 0..63 passes, 0..64 fails
}
```
like this :
```
   Compiling debug_bitbox2 v0.1.0 (/Users/kulp/Documents/Code/Rust/debug_bitbox2)
    Finished test [unoptimized + debuginfo] target(s) in 0.94s
     Running target/debug/deps/debug_bitbox2-c997261e3972ef97

running 1 test
test fails_with_u64 ... FAILED

failures:

---- fails_with_u64 stdout ----
thread 'fails_with_u64' panicked at 'attempt to shift left with overflow', /Users/kulp/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.17.4/src/fields.rs:579:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    fails_with_u64

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
```
whereas using a `u32` (or smaller) type to initialize the `BitBox` does not panic.

It smells like a fencepost error, given that `boxed[0..63]` passes while `boxed[0..64]` fails.

This occurs for me both on macOS 10.14.6 and on Arch Linux, with `rustc 1.42.0 (b8cedc004 2020-03-09)`.

**Comment by kulp** [comment]
I should clarify that "using a `u32` ..." makes sense only if the range is changed from the one I wrote. The original range where I found the issue was simply `boxed[..]`. Later I discovered the behavioral difference between `[..63]` and `[..64]`.

**Comment by myrrlyn** [comment]
Something isn't calling [`mask_for`](https://github.com/myrrlyn/bitvec/blob/v0.17.4/src/fields.rs#L873-L882) like it should be. I'll chase it down, thanks.

**Comment by myrrlyn** [comment]
I found the issue; the load/store implementations were attempting to shift the accumulator value by the width of the transfer type, which causes a runtime error when the `BitSlice<_, T>::load::<M>` types `T` and `M` are the same width. I have fixed this in my development branch by removing the shift when it would cause overflow.

I want to keep the behavior that a bit slice fully spanning an element is a `Region`, not an `Enclave`, as this avoids needless aliasing in `Domain` views.

**Comment by kulp** [comment]
> I want to keep the behavior that a bit slice fully spanning an element is a `Region`, not an `Enclave`, as this avoids needless aliasing in `Domain` views.

I will have to take your word for it. I think it would be wise at least to add this specific case to [your document](https://github.com/myrrlyn/bitvec/blob/e1cc5cf6d289a5b17c16eeddd0f3eb8ed019b18d/doc/Memory%20Model.md#bit-slice-domains) since it is still not clear into which of the nine cases in your diagram this case is supposed to fall.

**Comment by myrrlyn** [comment]
Can you test if current `develop` works correctly for you? Sorry for the delay; it's been. Quite the year.

**Comment by kulp** [comment]
> Can you test if current `develop` works correctly for you?

I started to test my original (private) code using
```toml
bitvec = { git = "https://github.com/myrrlyn/bitvec.git", branch = "develop" }
```
but I immediately noticed some API differences : 
```
error[E0599]: no method named `bits` found for type `u32` in the current scope
  --> src/lib.rs:30:46
   |
30 |             bv.extend_from_slice(u.to_bits().bits::<Lsb0>());
   |                                              ^^^^ method not found in `u32`
```
and also
```
error[E0277]: can't compare `&bitvec::slice::BitSlice` with `bitvec::vec::BitVec`
   --> src/lib.rs:293:34
    |
293 |                 } else if header == bitvec![0, 0] {
    |                                  ^^ no implementation for `&bitvec::slice::BitSlice == bitvec::vec::BitVec`
    |
    = help: the trait `std::cmp::PartialEq<bitvec::vec::BitVec>` is not implemented for `&bitvec::slice::BitSlice`
```
I just wanted to check first whether these API differences are expected before I go to effort to port to the new API.

> Sorry for the delay; it's been. Quite the year.

No big deal from my perspective. Thanks for your work on `bitvec`.

**Comment by myrrlyn** [comment]
Yes, the trait renames are [marked in the CHANGELOG](https://github.com/myrrlyn/bitvec/blob/develop/CHANGELOG.md#changed-), and I will restore the names for a deprecation cycle.

The equality failure is weird. That *should* work, and clearly my attempt to refactor these implementations dropped some support that I will restore. I will also emphasize in the documentation that `bits!` should be preferred over `bitvec!` for the construction of a literal sequence that will not be used as a persistent buffer.

**Comment by myrrlyn** [comment]
I believe that equality is now as broadly-implemented as I can get it. If you are still having equality issues in 0.18, please file an issue again; as the `BitField` implementation is now correct; I am going to close this issue. Thanks again for the report!
